title: "Shikhar Kumar"
description: "Mechanical Engineer | CAD & Simulation | Lightweight Structures | Scania Thesis on EV Battery Frames"
theme: jekyll-theme-minimal

url: "https://shikhar2497.github.io"
linkedin_username: shikhar-kumar97
github_username: Shikhar2497
email: shikhark@kth.se
